# Name of your blog (this will show up at the top of your page and in the RSS feed)
name: WebIDE

# Short description (goes below the title; it will also be used in the RSS feed)
description: Welcome to the WebIDE Docs! A portable IDE written in html!!!

# Your name, as you want it to appear underneath each post and in the footer
author: Joseph Robinson

# Your email if you want it to be linked on the contact page
author_email: smartech56@gmail.com

# The directory for category index pages. Change it to something else if
# for example you want links like /categories/category1 instead of /category1
category_dir: /

# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
url: https://josephworks.github.io

#### Under the Hood Stuff #####

# Makes pretty (descriptive) permalinks. See Jekyll docs for alternatives.
permalink: pretty

# How many articles do you wish to appear on the front page:
paginate: 3

theme: jekyll-theme-slate
plugins:
  - jekyll-gist
  - jekyll-coffeescript
  - jekyll-assets
  - jekyll-sitemap
